export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorForButtonGray: "#F7F7F7",
  colorForLightBackground: "#D8ECFE",
  colorForDarkBackground: "#ffeead",
  colorForAbout: "#c4e2ff",
  colorForNegativeLight: "#F8DDD7",
  colorForNegativeDark: "#F75531",
  colorForPositiveLight: "#E1EDCE",
  colorForPositiveDark: "#88AA4D",
  colorForButton: "#FC9B27",
  colorForButtonHover: "#FC7427",
  colorForBackgroundBuyPage: "#F7F7F7",
  colorForPrice: "#D8ECFE",
  panelBackgroundColor: "#88aa4d",
  panelBackgroundColorDanger: "#f75531",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1280px",
  backgroundColorBlue: "#d8ecfe",
  buttonColor: "#fc9b27",
  buttonColorHoverActive: "#fc7427",
  lineHeightDefault: 1.5,
  headerHeight: "80px"
};
